---
title: "Eating differently"
date: 2012-12-12
date-modified: 2026-03-08
author: Jonathan Whitmore
draft: true
categories: []
---

I've been inspired to write up a bit about what I have been eating. The long and the short of it is that I'm basically following the "Paleo"/"Primal" diet (since July 2012), for health reasons (as in my goal was not for weight loss).

It breaks down into two lists: the "allowed/encouraged" and "not allowed". Here's how I play it:
### ALLOWED

	
- fish
	
- meat
	
- fowl
	
- eggs
	
- bacon
	
- avocados
	
- greens (love me some spinach!)
	
- fruits
	
- vegetables (bell peppers, zucchini, onions, etc.)
	
- nuts (almonds, walnuts, pine nuts)
	
- oil (olive oil, avocado oils, coconut oil)
	
- vinegars (balsamic, etc.)
	
- tea


### NOT ALLOWED

	
- no grains (flour, wheat, cereals, etc.)
	
- no potatoes
	
- no legumes (peanuts, soy)
	
- no beans
	
- no corn
	
- no refined sugar
	
- semi-restricted dairy (butter and cheese are fine for me)


A small rant about the name. Paleo is short for paleolithic, as in the time period. It is also referred to as "caveman" diet and probably a few other names. I dislike this name because I find it misleading and unhelpful. The reason I do or do not eat the above things is that I've found it to be healthy to eat (or avoid) the above lists of food. **That's it.** Not for any other reason that's justified because "we evolved to eat this way" or other such claims. I do suspect that there's something to the idea that grains (not just gluten) can cause reactions in some people like an inflammation response.

I don't want to go into the details, but I just want to say that I've found that following these rules has been beneficial to me. As a scientist, I insist that my anecdote isn't conclusive evidence, but it might lead to some interesting future experiments.

Also note that I decided to follow this diet after watching the following TED talk and reading a number of resources (which didn't all agree). I decided that at the worst the diet was healthy (and likely healthier than I was eating at the time). At best, it could improve my health.

**Free resources**

	
- [http://www.marksdailyapple.com/](http://www.marksdailyapple.com/)
	
- [http://www.reddit.com/r/paleo](http://www.reddit.com/r/paleo)


**Books**

	
- [The Primal Blueprint](http://www.amazon.com/The-Primal-Blueprint-effortless-ebook/dp/)
	
- [Perfect Health Diet](http://www.amazon.com/Perfect-Health-Diet-ebook/dp/)



**TEDxIowaCity Dr. Terry Wahls**


{{< video http://www.youtube.com/embed/KLjgBLwH3Wc >}}

Your mileage may vary/buyer beware/consult doctor before changing stuff.
